### ISSUE TITLE
add routes for PATCH method

### ISSUE THREAD

**Issue by ivanhuay** [ivanhuay/hiroki#4]
implement some interface for update only one field.

**Comment by ivanhuay** [comment]
should this fire `post('save'` method? 🤔 maybe not

**Comment by ivanhuay** [comment]
probably this could replace the `fastUpdate` option https://ivanhuay.github.io/hiroki/configuration/configuration/

**Comment by ivanhuay** [comment]
this is not so useful so if someone want this in the future i'll reopen this

**Comment by HernanGH** [comment]
I think it's very usefull for the all developers. you need more work.
